# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-01 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Unnamed', max_length=100)),
                ('image_filename', models.CharField(default=b'', max_length=100)),
                ('breed', models.CharField(default=b'Unknown', max_length=100)),
                ('age', models.IntegerField(blank=True, default=1)),
                ('gender', models.CharField(choices=[(b'm', b'male'), (b'f', b'female'), (b'u', b'unknown')], default=b'u', max_length=1)),
                ('size', models.CharField(choices=[(b's', b'small'), (b'm', b'medium'), (b'l', b'large'), (b'xl', b'extra large'), (b'u', b'unknown')], default=b'u', max_length=1)),
                ('behaviour', models.CharField(choices=[(b'c', b'confident'), (b's', b'shy'), (b'i', b'independent'), (b'h', b'happy'), (b'a', b'aggressive'), (b'u', b'unknown')], default=b'u', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'l', b'liked'), (b'd', b'disliked'), (b'u', b'undecided')], max_length=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pugorugh.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default=b'b,y,a,s', help_text=b"Options are: 'b,y,a,s' for baby, young, adult and senior.", max_length=7)),
                ('gender', models.CharField(default=b'm,f', help_text=b"Options are: 'm,f' for male and female.", max_length=3)),
                ('size', models.CharField(default=b's,m,l,xl', help_text=b"Options are 's,m,l,xl' for small, medium, large and extra large", max_length=8)),
                ('behaviour', models.CharField(default=b'c,s,i,h,a', help_text=b"Options are 'c,s,i,h,a' for confident, shy, independent, happy and aggressive.", max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
