# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
